# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d646a8848110b5e56a709c79dc0551bd62ba6d42e14ec0726000e105867a6cd58eae341807c58daffe7ef8ec816002434e9351ad9f9f0b55d1d2da216a0d6f54

test:
  secret_key_base: d424e4e2193bbb11fdc6388036829a7e81ec4b6b469beca659ba91211db4c797e473f8802ceb32803f70f8ffac8d9b677a2d85a9f3c85f0ec1dc2e0f09c09e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
